- name: Install Node.js on EC2 instance
  hosts: ec2_instance
  gather_facts: no
  become: yes
  vars:
    ansible_ssh_private_key_file: /home/runner/.ssh/id_rsa
    ansible_python_interpreter: /usr/bin/python3
    ansible_user: ubuntu
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'
  tasks:
    - name: Wait for SSH to come up
      wait_for:
        host: "{{ inventory_hostname }}"
        port: 22
        delay: 60
        timeout: 900
        state: started

    - name: Gathering Facts
      setup:
    - name: Update all packages
      dnf:
        name: '*'
        state: latest
    - name: Install Docker
      apt:
        name: docker.io
        update_cache: yes

    - name: Package Installer For Python3 
      package:
        name: python3
        state: present

    - name: Installing python library for the Docker Remote API
      pip:
        name: docker-py


    - name: Start Docker Service
      service:
        name: docker
        state: started
        enabled: yes

    - name: Run Docker Container
      docker_container:
        name: my_container
        image: your_docker_image
        state: started
