name: Connection Test

on:
  push:
    branches:
      - main

jobs:
  connection_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Ansible
        run: pip install ansible

      - name: Run Ansible Playbook
        env:
          PRIVATE_IP: ${{ secrets.MYPLUBICIP }}
          PRIVATE_KEY: ${{ secrets.MYPRIVATEKEY }}    

      - name: Run Ansible Connection Test      
        run: |
         echo "$PRIVATE_KEY" > /tmp/private_key.pem
         chmod 600 /tmp/private_key.pem   
         ansible-playbook -i inventory.ini test_connection.yml
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        if: matrix.os == 'ubuntu-latest'
